#Se recomienda confirar los secretos con external secrets helm v5

variables:

  common:
    config: {}
    secret: {}

global:
  environment: "development"
  replicaCount: "1"
  revisionHistoryLimit: "5"
  minReadySeconds: "0"
  version: "v1"

container:
  project: "development"
  registry: "gcr.io"
  tag: "2019.11.25-16.30.32"
  pullPolicy: "IfNotPresent"
  livenessProbe:
    exec:
      command:
        - /bin/sh
        - -c
        - |
          if [ "$(curl -s http://localhost:8080/evaluacion-api1-orlando-mejia/actuator/health | cut -d "{" -f 2 | cut -d "}" -f 1 | cut -d "," -f 1 )" != '"status":"UP"' ];then exit 1; fi
    initialDelaySeconds: 90
    periodSeconds: 10
    failureThreshold: 12
  readinessProbe:
    exec:
      command:
        - /bin/sh
        - -c
        - |
          if [ "$(curl -s http://localhost:8080/evaluacion-api1-orlando-mejia/actuator/health | cut -d "{" -f 2 | cut -d "}" -f 1 | cut -d "," -f 1 )" != '"status":"UP"' ];then exit 1; fi
    initialDelaySeconds: 90
    periodSeconds: 10
    failureThreshold: 12
  resources:
    requests:
      cpu: 50m
      memory: 384Mi
    limits:
      #cpu: 250m
      memory: 768Mi
  port:
    - name: msa-port
      servicePort: 80
      containerPort: 8080
      protocol: TCP
  volumeMounts:
    - name: init-sh
      mountPath: /opt/build/init.sh
      subPath: init.sh

hpa:
  minReplicas: 1
  maxReplicas: 1
  targetMemory: 768Mi

pdb:
  minAvailable: 1

volumes:
  - name: init-sh
    configMap:
      name: configmap-staffing
      items:
        - key: init.sh
          path: init.sh
