openapi: 3.0.3
info:
  title: Evaluacion - Orlando Mejia
  description: |-
    POC - Validation of naming in Microservices
  termsOfService: http://swagger.io/terms/
  contact:
    email: orlando.mejia@globant.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/ORLANDOMEJIA_1/BPContractProjects/1.0.0
  - url: https://projectstore3.swagger.io/api/v3
tags:
  - name: Authentication
    description: Everything about your project
    externalDocs:
      description: Find out more
      url: http://swagger.io
paths:
  /auth/log-in/{user}{password}:
    post:
      tags:
        - Authentication
      summary: Finds Repo by name
      description: Get Repo by name
      operationId: GetProjectByName
      parameters:
        - name: user
          in: path
          description: Name values that need to be considered for filter
          required: true
          schema:
            type: string
        - name: password
          in: path
          description: Name values that need to be considered for filter
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ResponseDTO"
        "405":
          description: Invalid input
components:
  schemas:
    ResponseDTO:
      properties:
        message:
          type: string
        state:
          type: string
