openapi: 3.0.3
info:
  title: Evaluacion - Orlando Mejia
  description: |-
    POC - Validation of naming in Microservices
  termsOfService: http://swagger.io/terms/
  contact:
    email: orlando.mejia@globant.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/ORLANDOMEJIA_1/BPContractProjects/1.0.0
  - url: https://projectstore3.swagger.io/api/v3
tags:
  - name: SaveData
    description: Everything about your project
    externalDocs:
      description: Find out more
      url: http://swagger.io
paths:
  /save/data:
    post:
      tags:
        - SaveData
      summary: Finds Repo by name
      description: Get Repo by name
      operationId: GetProjectByName
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeviceRegistrationInfo'
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ResponseDTO"
        "405":
          description: Invalid input
components:
  schemas:
    ResponseDTO:
      properties:
        message:
          type: string
        state:
          type: string
    DeviceRegistrationInfo:
      type: object
      properties:
        token:
          type: string
          format: uri
          example: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c'
        estructuraJson:
          type: object
          properties:
            campo1:
              type: string
              format: uri
              example: 'valor1'
            campo2:
              type: string
              format: uuid
              example: 'valor1'
            campo3:
              type: string
              format: uuid
              example: 'valor1'
